import type { ToolPlugin } from './types'

export const toolRegistry: ToolPlugin[] = [
  {
    id: 'text-to-markdown',
    name: 'Text to Markdown',
    description: 'Transform any raw text, data, code, or document into clean, beautifully formatted Markdown with GitHub-style preview.',
    category: 'text',
    accepts: ['text/plain', 'text/csv', 'text/html', 'application/json', 'text/xml', 'application/xml', 'text/markdown', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    badge: 'Native JS',
    maxFileSize: 10 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    requiresFile: false,
    load: () => import('../../features/text-tools/text-to-markdown-tool').then((m) => m.default),
    capabilities: () => ({ supported: true })
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    category: 'image',
    description: 'Resize, upscale, compress, and convert PNG, JPG, WebP, and AVIF images.',
    badge: 'Canvas API',
    accepts: ['image/png', 'image/jpeg', 'image/webp', 'image/avif'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: true,
    featured: true,
    load: () => import('../../features/image-tools/image-resizer-tool').then((module) => module.default),
    capabilities: () => ({
      supported: typeof window !== 'undefined' && 'createImageBitmap' in window,
      reason: 'This browser does not support modern image decoding APIs.',
    }),
  },
  {
    id: 'csv-json-converter',
    name: 'CSV <-> JSON',
    category: 'data',
    description: 'Convert spreadsheets, JSON arrays, or pasted text both ways with validation.',
    badge: 'PapaParse',
    accepts: ['text/csv', 'application/json', 'text/plain'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    featured: true,
    load: () => import('../../features/data-tools/csv-json-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'text-formatter',
    name: 'Text Formatter',
    category: 'text',
    description: 'Normalize line endings, trim indentation, and pretty-print JSON text.',
    badge: 'Native JS',
    accepts: ['text/plain', 'application/json', 'text/markdown'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/text-tools/text-formatter-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'pdf-merge',
    name: 'PDF Merge',
    category: 'pdf',
    description: 'Combine multiple PDFs into a single document with preserved order.',
    badge: 'pdf-lib',
    accepts: ['application/pdf'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: true,
    featured: true,
    load: () => import('../../features/pdf-tools/pdf-merge-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'pdf-split',
    name: 'PDF Split',
    category: 'pdf',
    description: 'Extract page ranges or split every page into standalone PDFs.',
    badge: 'pdf-lib',
    accepts: ['application/pdf'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: false,
    load: () => import('../../features/pdf-tools/pdf-split-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'video-to-mp3',
    name: 'MP4 to MP3',
    category: 'media',
    description: 'Extract audio locally using FFmpeg.wasm with worker-backed progress updates.',
    badge: 'FFmpeg.wasm',
    accepts: ['video/mp4', 'video/quicktime', 'video/x-m4v'],
    maxFileSize: 500 * 1024 * 1024,
    supportsBatch: false,
    featured: true,
    load: () => import('../../features/media-tools/video-to-mp3-tool').then((module) => module.default),
    capabilities: () => {
      const supported = typeof window !== 'undefined' && 'Worker' in window && 'WebAssembly' in window
      return {
        supported,
        reason: 'This browser cannot run the local FFmpeg worker required for media conversion.',
      }
    },
  },
  {
    id: 'find-replace',
    name: 'Find & Replace',
    category: 'text',
    description: 'Find and replace text using plain search or regular expressions.',
    badge: 'RegExp',
    accepts: ['text/plain', 'application/json', 'text/markdown', 'text/html', 'text/csv'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: true,
    load: () => import('../../features/text-tools/find-replace-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'case-converter',
    name: 'Case Converter',
    category: 'text',
    description: 'Convert text between title case, camelCase, snake_case, and more.',
    badge: 'Native JS',
    accepts: ['text/plain', 'application/json', 'text/markdown'],
    maxFileSize: 5 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/text-tools/case-converter-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'line-sorter',
    name: 'Line Sorter',
    category: 'text',
    description: 'Sort, shuffle, and deduplicate lines from pasted text or uploaded files.',
    badge: 'Native JS',
    accepts: ['text/plain', 'text/csv', 'text/markdown'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/text-tools/line-sorter-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    category: 'text',
    description: 'Measure words, characters, sentences, read time, and readability.',
    badge: 'Native JS',
    accepts: ['text/plain', 'text/markdown', 'text/html', 'application/json'],
    maxFileSize: 10 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/text-tools/word-counter-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'url-encoder',
    name: 'URL Encode / Decode',
    category: 'text',
    description: 'Encode or decode URI components, full URLs, base64, and query strings.',
    badge: 'Native JS',
    accepts: ['text/plain'],
    maxFileSize: 1 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/text-tools/url-encoder-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    category: 'text',
    description: 'Decode JWT headers and payloads locally without sending tokens anywhere.',
    badge: 'Base64URL',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: true,
    requiresFile: false,
    load: () => import('../../features/text-tools/jwt-decoder-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'number-base-converter',
    name: 'Number Base Converter',
    category: 'developer',
    description: 'Convert binary, octal, decimal, hex, and custom-base numbers line by line.',
    badge: 'parseInt',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: true,
    requiresFile: false,
    load: () => import('../../features/developer-tools/number-base-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'slug-generator',
    name: 'Slug Generator',
    category: 'developer',
    description: 'Generate clean URL slugs from titles or bulk line-based input.',
    badge: 'Unicode',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: true,
    requiresFile: false,
    load: () => import('../../features/developer-tools/slug-generator-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'uuid-generator',
    name: 'UUID / ULID Generator',
    category: 'developer',
    description: 'Generate bulk UUID v4, v1, ULID, or NANOID unique identifiers.',
    badge: 'Web Crypto',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: false,
    requiresFile: false,
    load: () => import('../../features/developer-tools/uuid-generator-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    category: 'developer',
    description: 'Generate cryptographically secure passwords and passphrases.',
    badge: 'Web Crypto',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: false,
    requiresFile: false,
    load: () => import('../../features/developer-tools/password-generator-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    category: 'developer',
    description: 'Inspect regex matches or run regex-powered replacements locally.',
    badge: 'RegExp',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: true,
    requiresFile: false,
    load: () => import('../../features/developer-tools/regex-tester-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'base64-file-encoder',
    name: 'File Base64 Encoder',
    category: 'archive',
    description: 'Encode any file as raw base64, data URLs, CSS values, or JSON-safe strings.',
    badge: 'FileReader',
    accepts: ['*/*'],
    maxFileSize: 10 * 1024 * 1024,
    supportsBatch: false,
    load: () => import('../../features/archive-tools/base64-file-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'yaml-json-converter',
    name: 'YAML ↔ JSON',
    category: 'data',
    description: 'Convert YAML configuration files to JSON and vice versa.',
    badge: 'js-yaml',
    accepts: ['application/yaml', 'text/yaml', 'application/json', 'text/plain', 'application/x-yaml'],
    maxFileSize: 10 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/data-tools/yaml-json-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'xml-json-converter',
    name: 'XML ↔ JSON',
    category: 'data',
    description: 'Convert XML documents to JSON and back with attribute preservation.',
    badge: 'fast-xml-parser',
    accepts: ['application/xml', 'text/xml', 'application/json', 'text/plain'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/data-tools/xml-json-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'markdown-html-converter',
    name: 'Markdown ↔ HTML',
    category: 'text',
    description: 'Convert Markdown documents to HTML and HTML back to Markdown.',
    badge: 'marked',
    accepts: ['text/markdown', 'text/html', 'text/plain'],
    maxFileSize: 10 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/text-tools/markdown-html-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'html-entity-coder',
    name: 'HTML Entity Coder',
    category: 'text',
    description: 'Encode special characters to HTML entities and decode them back.',
    badge: 'he',
    accepts: ['text/plain', 'text/html'],
    maxFileSize: 5 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/text-tools/html-entity-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'cron-parser',
    name: 'Cron Expression Parser',
    category: 'developer',
    description: 'Parse cron expressions and show the next N execution times.',
    badge: 'cron-parser',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: true,
    requiresFile: false,
    load: () => import('../../features/developer-tools/cron-parser-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    category: 'developer',
    description: 'Generate placeholder text in words, sentences, or paragraphs.',
    badge: 'lorem-ipsum',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: false,
    requiresFile: false,
    load: () => import('../../features/developer-tools/lorem-ipsum-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'csv-excel-converter',
    name: 'CSV ↔ Excel',
    category: 'data',
    description: 'Convert between CSV and Excel formats with customizable delimiters and auto-sizing.',
    badge: 'SheetJS',
    accepts: ['text/csv', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/data-tools/csv-excel-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'json-excel-converter',
    name: 'JSON ↔ Excel',
    category: 'data',
    description: 'Convert nested JSON arrays to Excel or extract Excel rows to JSON.',
    badge: 'SheetJS',
    accepts: ['application/json', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'application/vnd.ms-excel'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/data-tools/json-excel-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'image-crop-rotate',
    name: 'Image Crop & Rotate',
    category: 'image',
    description: 'Crop pixel regions and rotate images by 90-degree increments locally.',
    badge: 'Canvas API',
    accepts: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: false,
    load: () => import('../../features/image-tools/image-crop-rotate-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'image-format-converter',
    name: 'Image Format Converter',
    category: 'image',
    description: 'Convert between JPEG, PNG, and WebP with optional transparency fills.',
    badge: 'Canvas API',
    accepts: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: false,
    load: () => import('../../features/image-tools/image-format-converter-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'image-watermark',
    name: 'Image Watermark',
    category: 'image',
    description: 'Add text watermarks to images with customizable font sizes and alignments.',
    badge: 'Canvas API',
    accepts: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: false,
    load: () => import('../../features/image-tools/image-watermark-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    category: 'image',
    description: 'Compress images using quality sliders or exact file-size targeting.',
    badge: 'Canvas API',
    accepts: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: false,
    load: () => import('../../features/image-tools/image-compressor-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'image-to-base64',
    name: 'Image ↔ Base64',
    category: 'image',
    description: 'Base64 encode images for CSS embedding or decode Data URIs to files.',
    badge: 'Canvas API',
    accepts: ['image/*', 'text/plain'],
    maxFileSize: 25 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/image-tools/image-to-base64-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    category: 'image',
    description: 'Turn a single square image into a multi-resolution favicon bundle.',
    badge: 'Canvas API',
    accepts: ['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml'],
    maxFileSize: 10 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/image-tools/favicon-generator-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    category: 'pdf',
    description: 'Render PDF pages locally to standard JPEG, PNG, or WebP formats.',
    badge: 'pdfjs-dist',
    accepts: ['application/pdf'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/pdf-tools/pdf-to-image-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'watermark-pdf',
    name: 'Watermark PDF',
    category: 'pdf',
    description: 'Add adjustable, transparent text watermarks to all PDF pages locally.',
    badge: 'pdf-lib',
    accepts: ['application/pdf'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/pdf-tools/watermark-pdf-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    category: 'pdf',
    description: 'Combine multiple images into a single PDF with auto-resizing and margins.',
    badge: 'pdf-lib',
    accepts: ['image/jpeg', 'image/png', 'image/webp', 'image/avif'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: false,
    load: () => import('../../features/pdf-tools/image-to-pdf-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    category: 'developer',
    description: 'Calculate cryptographic hashes (SHA-1 to SHA-512, MD5) of files or text locally.',
    badge: 'Web Crypto API',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: true,
    requiresFile: false,
    load: () => import('../../features/developer-tools/hash-generator-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'hmac-generator',
    name: 'HMAC Generator',
    category: 'developer',
    description: 'Generate Hash-based Message Authentication Codes (HMAC) using a secret key.',
    badge: 'Web Crypto API',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: true,
    requiresFile: false,
    load: () => import('../../features/developer-tools/hmac-generator-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'mock-data-generator',
    name: 'Mock Data Generator',
    category: 'data',
    description: 'Generate realistic dummy data entries exported as JSON, CSV, or SQL.',
    badge: 'Offline',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: false,
    requiresFile: false,
    load: () => import('../../features/data-tools/mock-data-generator-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'zip-extractor',
    name: 'ZIP Extractor',
    category: 'archive',
    description: 'Extract loose files from a ZIP archive locally and download them.',
    badge: 'JSZip',
    accepts: ['application/zip', 'application/x-zip-compressed'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/archive-tools/zip-extractor-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'zip-creator',
    name: 'ZIP Creator',
    category: 'archive',
    description: 'Compress multiple files into a single ZIP archive locally.',
    badge: 'JSZip',
    accepts: [],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: false,
    load: () => import('../../features/archive-tools/zip-creator-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'url-parser',
    name: 'URL Parser',
    category: 'developer',
    description: 'Break down absolute or relative URLs into structured components locally.',
    badge: 'Offline',
    accepts: ['text/plain'],
    maxFileSize: 1 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/developer-tools/url-parser-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'color-converter',
    name: 'Color Converter',
    category: 'developer',
    description: 'Convert between Hex, RGB, HSL, CMYK, and named colors instantly.',
    badge: 'color-convert',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: true,
    requiresFile: false,
    load: () => import('../../features/developer-tools/color-converter-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    category: 'developer',
    description: 'Generate customizable 2D QR codes with variable error correction and SVG export.',
    badge: 'qrcode',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: true,
    requiresFile: false,
    load: () => import('../../features/developer-tools/qr-generator-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    category: 'developer',
    description: 'Create customizable 1D barcodes like EAN, UPC, and CODE128 in vector SVG format.',
    badge: 'jsbarcode',
    accepts: [],
    maxFileSize: 0,
    supportsBatch: false,
    supportsPaste: true,
    requiresFile: false,
    load: () => import('../../features/developer-tools/barcode-generator-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'audio-converter',
    name: 'Audio Converter',
    category: 'media',
    description: 'Transcode audio formats locally (MP3, WAV, AAC, OGG) and change bitrates using WebAssembly.',
    badge: 'ffmpeg.wasm',
    accepts: ['audio/*', 'video/*'],
    maxFileSize: 150 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: false,
    load: () => import('../../features/media-tools/audio-converter-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'pdf-page-reorder',
    name: 'PDF Page Reorder',
    category: 'pdf',
    description: 'Rearrange, delete, or duplicate pages in a PDF document locally.',
    badge: 'pdf-lib',
    accepts: ['application/pdf'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/pdf-tools/pdf-page-reorder-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'pdf-rotate',
    name: 'PDF Rotate Pages',
    category: 'pdf',
    description: 'Rotate all or specific pages in a PDF to any angle.',
    badge: 'pdf-lib',
    accepts: ['application/pdf'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/pdf-tools/pdf-rotate-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'pdf-metadata-editor',
    name: 'PDF Metadata Editor',
    category: 'pdf',
    description: 'View and edit PDF properties like title, author, subject, and keywords.',
    badge: 'pdf-lib',
    accepts: ['application/pdf'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/pdf-tools/pdf-metadata-editor-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'pdf-compress',
    name: 'PDF Compress',
    category: 'pdf',
    description: 'Reduce PDF file size by re-rendering pages at lower resolution (lossy).',
    badge: 'pdfjs-dist',
    accepts: ['application/pdf'],
    maxFileSize: 200 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/pdf-tools/pdf-compress-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'pdf-password',
    name: 'PDF Password Remove',
    category: 'pdf',
    description: 'Remove the password from a user-unlocked PDF (you must know it).',
    badge: 'pdf-lib',
    accepts: ['application/pdf'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/pdf-tools/pdf-password-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'pdf-form-flatten',
    name: 'PDF Form Flatten',
    category: 'pdf',
    description: 'Statically flatten interactive fillable form fields in a PDF into graphics.',
    badge: 'pdf-lib',
    accepts: ['application/pdf'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/pdf-tools/pdf-form-flatten-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'video-trimmer',
    name: 'Video Trimmer',
    category: 'media',
    description: 'Trim videos to a specific start or end time without re-encoding via FFmpeg.',
    badge: 'ffmpeg.wasm',
    accepts: ['video/mp4', 'video/quicktime', 'video/x-m4v', 'video/webm'],
    maxFileSize: 500 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/media-tools/video-trimmer-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'video-compressor',
    name: 'Video Compressor',
    category: 'media',
    description: 'Compress video files locally to reduce size using CRF quality mapping.',
    badge: 'ffmpeg.wasm',
    accepts: ['video/mp4', 'video/quicktime', 'video/webm'],
    maxFileSize: 500 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/media-tools/video-compressor-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'video-to-gif',
    name: 'Video to GIF',
    category: 'media',
    description: 'Convert short video clips into animated GIFs with optimized color palettes.',
    badge: 'ffmpeg.wasm',
    accepts: ['video/mp4', 'video/quicktime', 'video/webm'],
    maxFileSize: 200 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/media-tools/video-to-gif-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'audio-trimmer',
    name: 'Audio Trimmer',
    category: 'media',
    description: 'Trim audio files to exact timestamps and apply fade-in/out effects.',
    badge: 'ffmpeg.wasm',
    accepts: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/aac', 'audio/flac'],
    maxFileSize: 200 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/media-tools/audio-trimmer-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'gif-to-mp4',
    name: 'GIF to MP4',
    category: 'media',
    description: 'Convert bulky animated GIF files to tiny MP4 videos natively.',
    badge: 'ffmpeg.wasm',
    accepts: ['image/gif'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/media-tools/gif-to-mp4-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'video-frame-extractor',
    name: 'Video Frame Extractor',
    category: 'media',
    description: 'Extract specific frames or intervals from a video as PNG images in a ZIP.',
    badge: 'ffmpeg.wasm',
    accepts: ['video/mp4', 'video/quicktime', 'video/webm'],
    maxFileSize: 500 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/media-tools/video-frame-extractor-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'audio-normalizer',
    name: 'Audio Volume Normalizer',
    category: 'media',
    description: 'Normalize audio loudness strictly to EBU R128 (-23 LUFS) standard.',
    badge: 'ffmpeg.wasm',
    accepts: ['audio/mpeg', 'audio/wav', 'audio/ogg', 'audio/aac'],
    maxFileSize: 200 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/media-tools/audio-normalizer-tool').then((module) => module.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'batch-renamer',
    name: 'Batch File Renamer',
    category: 'archive',
    description: 'Rename multiple files with patterns, sequences, and find-replace rules.',
    badge: 'JSZip',
    accepts: ['*/*'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: false,
    load: () => import('../../features/archive-tools/batch-renamer-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'tar-creator',
    name: 'TAR Archive Creator',
    category: 'archive',
    description: 'Create .tar or .tar.gz archives from multiple files.',
    badge: 'fflate',
    accepts: ['*/*'],
    maxFileSize: 500 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: false,
    load: () => import('../../features/archive-tools/tar-creator-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'archive-inspector',
    name: 'Archive Inspector',
    category: 'archive',
    description: 'Inspect ZIP/TAR contents, sizes, and structure without extracting.',
    badge: 'JSZip',
    accepts: ['application/zip', 'application/x-zip-compressed', 'application/gzip'],
    maxFileSize: 500 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/archive-tools/archive-inspector-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'sql-csv',
    name: 'SQL over CSV',
    category: 'data',
    description: 'Run SQL queries against CSV files locally using SQLite WASM.',
    badge: 'sql.js',
    accepts: ['text/csv', 'text/plain'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/data-tools/sql-csv-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'image-bg-remover',
    name: 'Image BG Remover',
    category: 'image',
    description: 'Remove background from images locally using MediaPipe ML models.',
    badge: 'MediaPipe',
    accepts: ['image/jpeg', 'image/png', 'image/webp'],
    maxFileSize: 25 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: false,
    load: () => import('../../features/image-tools/image-bg-remover-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'file-hash-calculator',
    name: 'File Integrity Checker',
    category: 'archive',
    description: 'Compute checksums for files to verify integrity after transfer.',
    badge: 'Web Crypto',
    accepts: ['*/*'],
    maxFileSize: 2000 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: false,
    load: () => import('../../features/archive-tools/file-hash-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'exif-viewer',
    name: 'EXIF Viewer & Stripper',
    category: 'image',
    description: 'View all EXIF, IPTC, and XMP metadata in image files or strip it for privacy.',
    badge: 'exifr',
    accepts: ['image/jpeg', 'image/png', 'image/webp', 'image/tiff'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: false,
    load: () => import('../../features/image-tools/exif-viewer-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'color-picker-image',
    name: 'Color Picker from Image',
    category: 'image',
    description: 'Extract the dominant color palette from any image using k-means clustering.',
    badge: 'K-Means',
    accepts: ['image/jpeg', 'image/png', 'image/webp'],
    maxFileSize: 25 * 1024 * 1024,
    supportsBatch: false,
    load: () => import('../../features/image-tools/color-picker-image-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'sprite-sheet-builder',
    name: 'Sprite Sheet Builder',
    category: 'image',
    description: 'Pack multiple images into a single sprite sheet with CSS mapping.',
    badge: 'JSZip',
    accepts: ['image/jpeg', 'image/png', 'image/webp'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: true,
    load: () => import('../../features/image-tools/sprite-sheet-builder-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'toml-json-converter',
    name: 'TOML ↔ JSON',
    category: 'data',
    description: 'Convert between TOML and JSON configuration formats locally.',
    badge: '@iarna/toml',
    accepts: ['text/plain', 'application/json'],
    maxFileSize: 5 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/data-tools/toml-json-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'csv-merger',
    name: 'CSV Merger',
    category: 'data',
    description: 'Merge multiple CSV files by stacking rows or joining on a key column.',
    badge: 'PapaParse',
    accepts: ['text/csv', 'text/plain'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: true,
    load: () => import('../../features/data-tools/csv-merger-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'csv-deduplicator',
    name: 'CSV Deduplicator',
    category: 'data',
    description: 'Remove duplicate rows from CSV files based on one or all columns.',
    badge: 'Set Hash',
    accepts: ['text/csv', 'text/plain'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/data-tools/csv-dedup-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'csv-column-picker',
    name: 'CSV Column Picker',
    category: 'data',
    description: 'Select, reorder, or rename columns in a CSV file header.',
    badge: 'PapaParse',
    accepts: ['text/csv', 'text/plain'],
    maxFileSize: 100 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/data-tools/csv-column-picker-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'json-schema-validator',
    name: 'JSON Schema Validator',
    category: 'data',
    description: 'Validate JSON data against a JSON Schema draft-07 definition.',
    badge: 'AJV',
    accepts: ['application/json', 'text/plain'],
    maxFileSize: 10 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/data-tools/json-schema-validator-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'excel-formula-eval',
    name: 'Excel Formula Evaluator',
    category: 'data',
    description: 'Evaluate complex Excel formulas on uploaded spreadsheet data pools.',
    badge: 'HyperFormula',
    accepts: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'text/csv'],
    maxFileSize: 25 * 1024 * 1024,
    supportsBatch: false,
    load: () => import('../../features/data-tools/excel-formula-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'text-diff-viewer',
    name: 'Text Diff Viewer',
    category: 'text',
    description: 'Compare two text files or strings to find character-level differences.',
    badge: 'Myers Diff',
    accepts: ['text/plain'],
    maxFileSize: 10 * 1024 * 1024,
    supportsBatch: false,
    load: () => import('../../features/text-tools/text-diff-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'html-minifier',
    name: 'HTML Minifier',
    category: 'text',
    description: 'Compress HTML documents by removing whitespace, comments, and minifying scripts.',
    badge: 'Terser',
    accepts: ['text/html', 'text/plain'],
    maxFileSize: 25 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/text-tools/html-minifier-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'text-line-tools',
    name: 'Bulk Line Tools',
    category: 'text',
    description: 'Manipulate text by adding prefixes, filtering lines, or shuffling ranges.',
    badge: 'Native JS',
    accepts: ['text/plain'],
    maxFileSize: 50 * 1024 * 1024,
    supportsBatch: false,
    supportsPaste: true,
    load: () => import('../../features/text-tools/text-line-tools-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'svg-optimizer',
    name: 'SVG Optimizer',
    category: 'developer',
    description: 'Optimize vector SVG graphics by removing metadata and simplifying paths.',
    badge: 'SVGO',
    accepts: ['image/svg+xml'],
    maxFileSize: 10 * 1024 * 1024,
    supportsBatch: true,
    load: () => import('../../features/developer-tools/svg-optimizer-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier',
    category: 'developer',
    description: 'Compress and optimize CSS stylesheets using advanced merging rules.',
    badge: 'Clean-CSS',
    accepts: ['text/css', 'text/plain'],
    maxFileSize: 10 * 1024 * 1024,
    supportsBatch: true,
    supportsPaste: true,
    load: () => import('../../features/developer-tools/css-minifier-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
  {
    id: 'file-type-detector',
    name: 'File Type Detector',
    category: 'archive',
    description: 'Detect the real MIME type of any file using binary magic number signatures.',
    badge: 'Binary Probe',
    accepts: ['*/*'],
    maxFileSize: 1024 * 1024 * 1024,
    supportsBatch: false,
    load: () => import('../../features/archive-tools/file-type-detector-tool').then((m) => m.default),
    capabilities: () => ({ supported: true }),
  },
]

export function getToolById(toolId: string) {
  return toolRegistry.find((tool) => tool.id === toolId)
}
