import type { ToolModule, ToolOptionsComponentProps } from '../../core/plugins/types'
import { OptionsSection, OptionsSelect, OptionsTextArea } from '../../components/workspace/OptionsComponents'

interface FileHashOptions {
  algorithm: 'SHA-1' | 'SHA-256' | 'SHA-384' | 'SHA-512'
  compareList: string
  outputFormat: 'Text report' | 'JSON' | 'SFV file' | 'MD5SUMS format'
}

function FileHashOptionsComponent({ options, onChange }: ToolOptionsComponentProps<FileHashOptions>) {
  return (
    <>
      <OptionsSection label="Hash Settings">
        <div className="grid gap-4 sm:grid-cols-2">
          <OptionsSelect
            label="Hash Algorithm"
            value={options.algorithm}
            onChange={(val) => onChange({ ...options, algorithm: val as FileHashOptions['algorithm'] })}
            options={[
              { value: 'SHA-256', label: 'SHA-256 (Recommended)' },
              { value: 'SHA-1', label: 'SHA-1 (Legacy / Git)' },
              { value: 'SHA-384', label: 'SHA-384' },
              { value: 'SHA-512', label: 'SHA-512 (Highest security)' },
            ]}
          />
          <OptionsSelect
            label="Report Format"
            value={options.outputFormat}
            onChange={(val) => onChange({ ...options, outputFormat: val as FileHashOptions['outputFormat'] })}
            options={[
              { value: 'Text report', label: 'Plain Text List' },
              { value: 'MD5SUMS format', label: 'Standard Linux format' },
              { value: 'SFV file', label: 'SFV Checksum File' },
              { value: 'JSON', label: 'JSON Data Array' },
            ]}
          />
        </div>
      </OptionsSection>

      <OptionsSection label="Verification" noBorder>
        <OptionsTextArea
          label="Verify Checksums (Optional)"
          value={options.compareList}
          onChange={(val) => onChange({ ...options, compareList: val })}
          placeholder="Paste official checksums here to automatically verify your files. One per line."
          rows={4}
        />
        <p className="text-xs text-secondary mt-2">
          Calculates cryptographic integrity hashes using the Web Crypto API.
        </p>
      </OptionsSection>
    </>
  )
}

function bufToHex(buffer: ArrayBuffer) {
  return Array.prototype.map.call(new Uint8Array(buffer), x => ('00' + x.toString(16)).slice(-2)).join('')
}

const module: ToolModule<FileHashOptions> = {
  defaultOptions: { algorithm: 'SHA-256', compareList: '', outputFormat: 'Text report' },
  OptionsComponent: FileHashOptionsComponent,
  async run(files, options, helpers) {
    
    // Build compare map if present
    const compareMap: Record<string, string> = {}
    if (options.compareList && options.compareList.trim()) {
      const lines = options.compareList.split('\n')
      for (const line of lines) {
        const parts = line.trim().split(/\s+/)
        if (parts.length >= 1) {
          // Assume the hash is the longest alphanumeric string with characteristic length
          const possibleHashes = parts.filter(p => p.length >= 32 && /^[a-fA-F0-9]+$/.test(p))
          if (possibleHashes.length > 0) {
            compareMap[possibleHashes[0].toLowerCase()] = line
          }
        }
      }
    }

    const results = []
    let failedVerifications = 0
    let textReport = options.outputFormat === 'SFV file' ? '; Generated by Universal File Toolkit\n; ' + new Date().toISOString() + '\n' : ''
    
    for (const [i, input] of files.entries()) {
      helpers.onProgress({ phase: 'processing', value: (i + 0.5) / files.length, message: `Hashing ${input.name}` })
      
      const buffer = await input.file.arrayBuffer()
      const hashBuffer = await crypto.subtle.digest(options.algorithm, buffer)
      const hash = bufToHex(hashBuffer)
      
      let verified = true
      if (Object.keys(compareMap).length > 0) {
        if (!compareMap[hash.toLowerCase()]) {
          verified = false
          failedVerifications++
        }
      }

      results.push({
        filename: input.name,
        hash,
        size: input.file.size,
        verified: Object.keys(compareMap).length > 0 ? verified : undefined
      })
      
      if (options.outputFormat === 'Text report') {
        textReport += `File: ${input.name}\nSize: ${input.file.size} bytes\n${options.algorithm}: ${hash}\n`
        if (Object.keys(compareMap).length > 0) {
          textReport += `Verification: ${verified ? 'PASS' : 'FAIL (Mismatch or not found)'}\n`
        }
        textReport += '\n'
      } else if (options.outputFormat === 'MD5SUMS format') {
        textReport += `${hash}  ${input.name}\n`
      } else if (options.outputFormat === 'SFV file') {
        // Technically SFV is CRC32 but we can emit a similar hash mapping
        textReport += `${input.name} ${hash.substring(0, 8).toUpperCase()}\n`
      }
    }

    if (options.outputFormat === 'JSON') {
      textReport = JSON.stringify(results, null, 2)
    }

    helpers.onProgress({ phase: 'finalizing', value: 1, message: 'Done' })
    const outName = 'checksums' + (options.outputFormat === 'JSON' ? '.json' : options.outputFormat === 'SFV file' ? '.sfv' : '.txt')
    const blob = new Blob([textReport], { type: 'text/plain' })
    
    return {
      outputs: [{ id: crypto.randomUUID(), name: outName, blob, type: 'text/plain', size: blob.size }],
      preview: { kind: 'text', title: 'Calculated ' + options.algorithm + ' Checksums', summary: `Analysed ${files.length} file(s). ${failedVerifications > 0 ? `WARNING: ${failedVerifications} failed verification!` : ''}`, textContent: textReport, metadata: [{ label: 'Algorithm', value: options.algorithm }] }
    }
  },
}

export default module
